set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'davidhalter/jedi-vim'
Plugin 'Chiel92/vim-autoformat'
Plugin 'ervandew/supertab'
Plugin 'lifepillar/vim-solarized8'

call vundle#end()            " required
filetype plugin indent on    " required

syntax enable
set tabstop=4
set softtabstop=4
set expandtab
set smartindent   " Do smart autoindenting when starting a new line
set shiftwidth=4

set statusline+=%F
set laststatus=2
set number
set showcmd
set cursorline
filetype indent on
set wildmenu
set showmatch

" kj is a combination unlikely to be typed for any other occasion.
imap kj <ESC>
nmap k gk
nmap j gj

set noswapfile

let g:jedi#max_doc_height = 18
let g:jedi#show_call_signatures = 2
let g:jedi#popup_on_dot = 0
let g:jedi#use_tabs_not_buffers = 1
let g:jedi#auto_close_doc = 0

nnoremap gb :ls<CR>:b<Space>
nnoremap <C-n> :NERDTreeToggle<CR>
let g:SuperTabDefaultCompletionType = "context"

nmap <C-h> gT
nmap <C-l> gt

set background=dark
if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif
colorscheme solarized8

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
